scorecard:
  # Setting a global scorecard option
  output: text
  plugins:
    - basic:
        cr-manifest:
          - "deploy/crds/apps.m88i.io_v1alpha1_nexus_cr.yaml"
    - olm:
        cr-manifest:
          - "deploy/crds/apps.m88i.io_v1alpha1_nexus_cr.yaml"
        csv-path: "deploy/olm-catalog/nexus-operator/0.3.0/nexus-operator.v0.3.0.clusterserviceversion.yaml"
