flags:
  operator:
    paths:
      - pkg/
  operator-e2e:
    paths:
      - pkg/
coverage:
  status:
    project:
      operator:
        target: 75%
        flags:
          - operator
comment:
  require_changes: false
ignore:
  - "test/e2e"
  - "pkg/test"
  - "pkg/apis"
