flags:
  operator:
    paths:
      - pkg/
      - controllers/
      - api
coverage:
  status:
    patch:
      default:
        informational: true
      operator:
        informational: true
      operator-e2e:
        informational: true
    project:
      operator:
        target: auto
        base: auto
        threshold: 5%
        flags:
          - operator
comment:
  require_changes: true
ignore:
  - "pkg/test"
