flags:
  operator:
    paths:
      - pkg/
  operator-e2e:
    paths:
      - pkg/
coverage:
  status:
    patch:
      default:
        informational: true
      operator:
        informational: true
      operator-e2e:
        informational: true
    project:
      operator-e2e:
        target: auto
        base: auto
        threshold: 5%
        flags:
          - operator-e2e
      operator:
        target: auto
        base: auto
        threshold: 5%
        flags:
          - operator
comment:
  require_changes: true
ignore:
  - "test/e2e"
  - "pkg/test"
  - "pkg/apis"
