flags:
  operator:
    paths:
      - pkg/
  operator-e2e:
    paths:
      - pkg/
coverage:
  status:
    patch:
      default:
        informational: true
      operator:
        informational: true
    project:
      operator:
        target: 75%
        informational: true
        flags:
          - operator
comment:
  require_changes: true
ignore:
  - "test/e2e"
  - "pkg/test"
  - "pkg/apis"
