apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nexus.apps.m88i.io
spec:
  group: apps.m88i.io
  names:
    kind: Nexus
    listKind: NexusList
    plural: nexus
    singular: nexus
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Nexus is the Schema for the nexus API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: NexusSpec defines the desired state of Nexus
          properties:
            credentials:
              description: NexusCredentials is the credentials for the administrator
                user in the Nexus web console
              properties:
                password:
                  minLength: 5
                  type: string
                user:
                  minLength: 5
                  type: string
              required:
              - password
              - user
              type: object
            image:
              description: Image is the full image tag name for this specific deployment
              minLength: 5
              type: string
            persistence:
              description: NexusPersistence is the structure for the data persistent
              properties:
                persistent:
                  type: boolean
                volumeSize:
                  type: string
              required:
              - persistent
              type: object
            replicas:
              description: Replicas is a number of Nexus pod replicas
              maximum: 100
              minimum: 1
              type: integer
            resources:
              description: NexusResources is the request and limit definitions for
                the deployed pods
              properties:
                cpuLimit:
                  type: string
                cpuRequest:
                  type: string
                memoryLimit:
                  type: string
                memoryRequest:
                  type: string
              type: object
          required:
          - credentials
          - image
          - persistence
          - replicas
          type: object
        status:
          description: NexusStatus defines the observed state of Nexus
          properties:
            adminUser:
              description: AdminUser is the administrator username
              type: string
            condition:
              description: Condition is the general condition status for the Nexus
                deployment
              type: string
            host:
              description: Host is Nexus Web Console URL
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
