kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nexus-operator
subjects:
- kind: ServiceAccount
  name: nexus-operator
  namespace: nexus-e2e
roleRef:
  kind: ClusterRole
  name: nexus-operator
  apiGroup: rbac.authorization.k8s.io
