apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: allow-nexus-userid-200
fsGroup:
  ranges:
    - max: 200
      min: 200
  type: MustRunAs
runAsUser:
  type: MustRunAs
  uid: 200
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  ranges:
    - max: 200
      min: 200
  type: MustRunAs
volumes:
  - secret
