name: Go
on: [push]
jobs:

  test:
    name: PR Basic Checks
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod/cache
          key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-cache-

      - name: Mod Tidy
        run: |
          go mod tidy

      - name: Mod Vendor
        run: go mod vendor

      - name: FMT
        run: gofmt -s -l -w cmd/ pkg/ version/

      - name: Vet
        run: go vet ./...

      - name: Test Packages
        run: go test -mod=vendor ./pkg/... -count=1
